/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Contenido.Palabra;
import Juego.Rosco;
import Pistas.Compra;
import Pistas.Letras;
import Pistas.SegundaDefinicion;
import Usuario.Jugador;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class DialogEntrenamiento extends javax.swing.JDialog {

    Jugador J1;

    private static int numLetras;
    private LocalDateTime fecha;
    private static Jugador jugador;
    Rosco RoscoE;
    int op;
    String resCorrecta;

    /**
     * Creates new form DialogEntrenamiento
     */
    public DialogEntrenamiento(java.awt.Frame parent, boolean modal, int numeroLetras) throws IOException {
        super(parent, modal);
        initComponents();

        this.J1 = Pasapalabra.pre;
        this.jugador = J1;
        this.numLetras = numeroLetras; //numLetras
        fecha = LocalDateTime.now();
        this.nombreE.setText(J1.getNombre());

        RoscoE = new Rosco(numLetras);
        this.MiLetraE.setText(RoscoE.PosicionActual().getInicial());
    }

    public void FinPartida() {
        String Mensaje = "Has terminado el entrenamiento \n";
        if (RoscoE.isTodoCorrecto()) {
            Mensaje += "¡¡Enhorabuena!! " + jugador.getNombre() + " HAS ACERTADO TODAS LAS LETRAS\n";
        }

        if (jugador.getPuntos() == 0) {
            Mensaje += "Has ganado 5 puntos porque no tenias ninguno\n";
            jugador.setPuntos(5);
        }
        JOptionPane.showMessageDialog(null, Mensaje);
        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TextoRespuesta = new javax.swing.JTextField();
        TextoPregunta = new javax.swing.JLabel();
        TextoAccion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        HacerAccion = new javax.swing.JButton();
        nombreE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MiLetraE = new javax.swing.JLabel();
        ResponderE = new javax.swing.JButton();
        PasapalabraE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SegundaDefinicion = new javax.swing.JButton();
        CompraAyuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextoRespuesta.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        TextoPregunta.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        TextoPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoPregunta.setText("AQUÍ DEBE MOSTRAR LA PREGUNTA/ RESULTADO DE ESTA ETC");
        TextoPregunta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoAccion.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        TextoAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoAccion.setText("ACCIÓN");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jRadioButton1.setText("Mostrar Rosco Entero");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jRadioButton2.setText("Responder Pregunta");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        HacerAccion.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        HacerAccion.setText("Realizar acción");
        HacerAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HacerAccionActionPerformed(evt);
            }
        });

        nombreE.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        nombreE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreE.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setText("Letra:");

        MiLetraE.setFont(new java.awt.Font("Perpetua Titling MT", 3, 48)); // NOI18N
        MiLetraE.setText("Ñ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(MiLetraE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(HacerAccion)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MiLetraE, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HacerAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResponderE.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ResponderE.setText("RESPONDER");
        ResponderE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponderEActionPerformed(evt);
            }
        });

        PasapalabraE.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        PasapalabraE.setText("PASAPALABRA");
        PasapalabraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasapalabraEActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AYUDAS");

        SegundaDefinicion.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        SegundaDefinicion.setText("PISTA");
        SegundaDefinicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundaDefinicionActionPerformed(evt);
            }
        });

        CompraAyuda.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        CompraAyuda.setText("COMPRAR RESPUESTA");
        CompraAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CompraAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(SegundaDefinicion)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompraAyuda)
                    .addComponent(SegundaDefinicion))
                .addGap(25, 25, 25))
        );

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JUEGO DEL PASAPALABRA");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(PasapalabraE, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(TextoAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ResponderE, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextoRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(TextoAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ResponderE, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(TextoRespuesta))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasapalabraE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1167, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        op = 0;
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        op = 1;
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void HacerAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HacerAccionActionPerformed
        if (op == 0) {
            JOptionPane.showMessageDialog(null, RoscoE.mostrarRosco());
        } else if (op == 1) {
            this.TextoPregunta.setText(RoscoE.PosicionActual().getDefinicion1());
        }
    }//GEN-LAST:event_HacerAccionActionPerformed

    private void ResponderEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponderEActionPerformed
        String res = this.TextoRespuesta.getText();

        this.resCorrecta = RoscoE.PosicionActual().getPalabra().toString();
        if (res.equals(this.resCorrecta)) {
            JOptionPane.showMessageDialog(null, "Letra " + RoscoE.PosicionActual().getInicial() + " CORRECTA!!!");
            Palabra aux = RoscoE.PosicionActual();
            RoscoE.PosicionActual().setAcertada(true);

            //final de ronda
            if (RoscoE.isUltimo(aux)) {
                //AÑADIR VUELTA SI ESTAMOS EN LA PRIMERA
                if (RoscoE.getVuelta() == 1 && !(RoscoE.todoRespondido())) {
                    RoscoE.setVuelta(2);
                } else {
                    //SECUENCIA DE FIN DE PARTIDA
                    if (RoscoE.todoRespondido()) {
                        this.FinPartida();
                    }
                }
            }
            this.MiLetraE.setText(RoscoE.PosicionActual().getInicial());

            this.TextoPregunta.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Letra " + RoscoE.PosicionActual().getInicial() + " erronea");
            Palabra aux = RoscoE.PosicionActual();
            RoscoE.PosicionActual().setFallada(true);

            //final de ronda
            if (RoscoE.isUltimo(aux)) {
                //AÑADIR VUELTA SI ESTAMOS EN LA PRIMERA
                if (RoscoE.getVuelta() == 1 && !(RoscoE.todoRespondido())) {
                    RoscoE.setVuelta(2);
                } else {
                    //SECUENCIA DE FIN DE PARTIDA
                    if (RoscoE.todoRespondido()) {
                        this.FinPartida();
                    }
                }
            }
            this.MiLetraE.setText(RoscoE.PosicionActual().getInicial());
            this.TextoPregunta.setText("");
        }
        TextoRespuesta.setText(null);
    }//GEN-LAST:event_ResponderEActionPerformed

    private void PasapalabraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasapalabraEActionPerformed

        //final de ronda
        if (RoscoE.isUltimo(RoscoE.PosicionActual())) {
            //AÑADIR VUELTA SI ESTAMOS EN LA PRIMERA
            if (RoscoE.getVuelta() == 1) {
                RoscoE.setVuelta(2);
                JOptionPane.showMessageDialog(null, "Letra " + RoscoE.PosicionActual().getInicial() + " aplazada");
                RoscoE.PosicionActual().setAplazada(true);
                this.MiLetraE.setText(RoscoE.PosicionActual().getInicial());
                this.TextoPregunta.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Es la ultima vuelta, no puedes PasarPalabra");
            }
        }

    }//GEN-LAST:event_PasapalabraEActionPerformed

    private void SegundaDefinicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundaDefinicionActionPerformed

        if (RoscoE.PosicionActual().getDefinicion2().equals("_")) {
            Letras aleatoria = new Letras(RoscoE.PosicionActual());
            JOptionPane.showMessageDialog(null, "Letras sueltas: " + aleatoria.mostrarInfo() + "\nCoste: " + aleatoria.getPrecio());

        } else {
            SegundaDefinicion segg = new SegundaDefinicion();
            JOptionPane.showMessageDialog(null, "Segunda definición: " + segg.mostrarDefinicion(RoscoE.PosicionActual()) + "\nCoste: " + segg.getPrecio());

        }
    }//GEN-LAST:event_SegundaDefinicionActionPerformed

    private void CompraAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraAyudaActionPerformed
        Compra pista = new Compra();
        JOptionPane.showMessageDialog(null, "La palabra es: " + pista.mostrarInfo(RoscoE.PosicionActual()));

        Palabra aux = RoscoE.PosicionActual();
        RoscoE.PosicionActual().setAcertada(true);
        //final de ronda
        if (RoscoE.isUltimo(aux)) {
            //AÑADIR VUELTA SI ESTAMOS EN LA PRIMERA
            if (RoscoE.getVuelta() == 1 && !(RoscoE.todoRespondido())) {
                RoscoE.setVuelta(2);
            } else {
                //SECUENCIA DE FIN DE PARTIDA
                if (RoscoE.todoRespondido()) {
                    this.FinPartida();
                }
            }
        }

        this.MiLetraE.setText(RoscoE.PosicionActual().getInicial());

        this.TextoPregunta.setText("");

    }//GEN-LAST:event_CompraAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEntrenamiento dialog = null;
                try {
                    dialog = new DialogEntrenamiento(new javax.swing.JFrame(), true, numLetras);
                } catch (IOException ex) {
                    Logger.getLogger(DialogEntrenamiento.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompraAyuda;
    private javax.swing.JButton HacerAccion;
    private javax.swing.JLabel MiLetraE;
    private javax.swing.JButton PasapalabraE;
    private javax.swing.JButton ResponderE;
    private javax.swing.JButton SegundaDefinicion;
    private javax.swing.JLabel TextoAccion;
    private javax.swing.JLabel TextoPregunta;
    private javax.swing.JTextField TextoRespuesta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel nombreE;
    // End of variables declaration//GEN-END:variables
}
